services:
  postgres:
    image: postgres:17
    container_name: live-stream-postgres
    networks:
      - live-stream-network
    restart: always
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_DB: livestreaming_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  rtmp:
    build: ./nginx-rtmp
    image: tiangolo/nginx-rtmp
    container_name: rtmp-server
    networks:
      - live-stream-network
    ports:
      - "1935:1935"  #OBS phat RTMP
      - "8082:81" #HTTP de xem HLS (Video restream) tu HLS
    volumes:
      - ./data:/video
    depends_on:
      live-stream-website:
        condition: service_healthy

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - live-stream-network
    restart: always

  live-stream-website:
    container_name: live-stream-be
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '8081:8081'
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - live-stream-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/livestream/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=livestreaming_db
      - DB_USERNAME=postgres
      - DB_PASSWORD=1234

volumes:
  redis-data:
    driver: local

networks:
  live-stream-network:
    driver: bridge
