services:
  #Database
  postgres:
    image: postgres:17
    container_name: live-stream-postgres
    networks:
      - live-stream-network
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - /d/SpringBootProject/LiveStreamingSystem/postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_DB: livestreaming_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234

  #Hosting live stream
  rtmp:
    build: ./nginx-rtmp
    image: tiangolo/nginx-rtmp
    container_name: rtmp-server
    networks:
      - live-stream-network
    ports:
      - "1935:1935"  #OBS phat RTMP
      - "8082:81" #HTTP de xem HLS (index.m3u8) from OBS
    volumes:
      #- /d/SpringBootProject/LiveStreamingSystem/storage-video:/var/www/html/hls
      - ./hls:/var/www/html/hls  # Mount HLS directory để FFmpeg có thể ghi
    depends_on:
      live-stream-website:
        condition: service_healthy

  #Queue
  rabbitmq:
    image: rabbitmq:4-management
    ports:
      - "5672:5672" #Port connect to Spring
      - "15672:15672" #Port admin manage localhost:15672
    networks:
      - live-stream-network

  #Cache
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - live-stream-network
    restart: always

  #Backend
  live-stream-website:
    container_name: live-stream-be
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '8081:8081'
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      elasticsearch:
        condition: service_healthy
    networks:
      - live-stream-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/livestream/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=livestreaming_db
      - DB_USERNAME=postgres
      - DB_PASSWORD=1234

      - R2_ENDPOINT=${R2_ENDPOINT}
      - R2_ACCESSKEY=${R2_ACCESSKEY}
      - R2_SECRETKEY=${R2_SECRETKEY}
      - R2_PUBLIC_URL=${R2_PUBLIC_URL}

      - RABBITMQ_HOST=rabbitmq
      - VNP_SECRET_KEY=${VNP_SECRET_KEY}
      - VNP_TMNCODE=${VNP_TMNCODE}
      - OAUTH2-GOOGLE-CLIENT-ID=${OAUTH2-GOOGLE-CLIENT-ID}
      - OAUTH2-GOOGLE-CLIENT-SECRET=${OAUTH2-GOOGLE-CLIENT-SECRET}
    volumes:
      - ./hls:/var/www/html/hls  # Mount HLS directory để FFmpeg có thể ghi
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.19.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m #Limit Memories
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es-data:/usr/share/elasticsearch/data
    networks:
      - live-stream-network
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  kibana:
    image: docker.elastic.co/kibana/kibana:8.19.3
    container_name: kibana
    networks:
      - live-stream-network
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      elasticsearch:
        condition: service_healthy
volumes:
  redis-data:
    driver: local
  es-data:
    driver: local

networks:
  live-stream-network:
    driver: bridge
