spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:livestreaming_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:1234}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  cache:
    type: redis
  web:
    resources:
      static-locations: file:./hls/
  devtools:
    livereload:
      enabled: false
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: 5672
    username: guest
    password: guest
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

server:
  port: 8081
  servlet:
    context-path: /livestream

management:
  endpoints:
    web:
      exposure:
        include=health:
jwt:
  signer-key: "0gXvmZeoBj0FPk+2JHne1dOOe8NNY0vm9u3OvAJCC9TVzx+u3tEC/YwQ3Q7aRE0F"
logging:
  level:
    root: info
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG

cloudflare:
  r2:
    endpoint: ${R2_ENDPOINT}
    access-key: ${R2_ACCESSKEY}
    secret-key: ${R2_SECRETKEY}
    bucket: video-livestream
    public-url-id: ${R2_PUBLIC_URL}

rabbitmq:
  exchange: "video.transcode.exchange"
  transcode:
    live:
      queue: "video.transcode.live.queue"
      routing-key: "video.transcode.live"
    vod:
      queue: "video.transcode.vod.queue"
      routing-key: "video.transcode.vod"

vnpay:
  tmn-code: ${VNP_TMNCODE}
  secret-key: ${VNP_SECRET_KEY}
  version: 2.1.0
  command: pay
  otherType: other
  return-url:  https://magical-minnow-openly.ngrok-free.app/livestream/api/payment/payment_callback