worker_processes auto;
rtmp_auto_push on;
events {}
rtmp {
    server {
        listen 1935;
        listen [::]:1935 ipv6only=on;
        chunk_size 4096;
        allow publish all;

        on_publish http://live-stream-be:8081/livestream/api/stream/on_publish;
        on_publish_done http://live-stream-be:8081/livestream/api/stream/finish;

        #on_publish http://localhost:8081/livestream/api/stream/on_publish;
        #on_publish_done http://localhost:8081/livestream/api/stream/finish;

        application live {

            live on;
            #record off;

            hls off;
            #hls_path /var/www/html/hls;
            #hls_fragment 10s; #Default is 5s
            #hls_playlist_length 5m; #Default is 30s
        }
    }
}

http {
    server {
        listen 81;
        location / {
            root /www;
        }

        location /hls {
            types {
                application/vnd.apple.mpegurl m3u8;
                application/octet-stream ts;
            }
            root /var/www/html;

            add_header Cache-Control no-cache;
            add_header Access-Control-Allow-Origin *;
        }

        location /dash {
            types {
                application/dash+xml mpd;
                video/mp4 mp4;
                video/webm webm;
            }
            root /var/www/html;

            add_header Cache-Control no-cache always;
            add_header Access-Control-Allow-Origin * always;
            add_header Access-Control-Allow-Methods "GET, OPTIONS" always;
            add_header Access-Control-Allow-Headers "Range" always;
            add_header Access-Control-Expose-Headers "Content-Length, Content-Range" always;
        }


    }
}

